### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by dfenstermaker** [tfiwm/jsdoc-loader#1]
I don't see documentation or anything for this, I am getting nothing out from the loader can you give some more detail on using this?

**Comment by dfenstermaker** [comment]
here is my jsdoc.conf by the way

{
    "opts": {
        "destination": "/docs"
    }
}

**Comment by MitkoTschimev** [comment]
hi ;)

this was an experiment with jsdoc and performace with webpack (it checked only if it was conform or contains errors). i found out that the npm jsdoc to heavy for a loader is. i am working on a jsdoc webpack plugin, because this is not called every file again. Only at the end. Please take a bit time. I am trying to release it this weekend. The plugin will support full jsdoc options.
